---
version: "2.1"
jobs:
  cat-config:
    docker:
      - image: alpine:3.12.1
    steps:
      - run:
          name: setup
          command: cat .circleci/config.yml
workflows:
  build:
    jobs:
      - cat-config
